# Generated by Django 3.2.25 on 2025-04-08 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.TextField()),
                ('to_date', models.TextField()),
                ('payment_status', models.TextField(default='pending')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lpgsubscription',
            name='next_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LPGOrder',
        ),
    ]
