# Generated by Django 3.2.25 on 2025-04-08 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpgsubscription',
            name='next_payment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
